name: Main
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 17 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: maven
      - name: Build
        run: mvn -B clean install -DskipTests

  integration-test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pulsar: [ 2.9.2, 2.10.0 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Run integration test
        run: integration-test/run-integration-test.sh
        env:
          PULSAR_VERSION: ${{ matrix.pulsar }}
